export const DEFAULT_COMPANY_SETTINGS = {
  name: "JDM PARTS",
  slogan: "Запчасти для Toyota, Lexus, Hyundai и Kia",
  logoText: "JDM PARTS",
  logoSubtitle: "Toyota • Lexus • Hyundai • Kia",
  phone1: "+7 777 123 45 67",
  phone2: "+7 701 123 45 67",
  whatsapp: "+7 777 123 45 67",
  email: "info@jdmparts.kz",
  address: "г. Алматы, ул. Абая 100",
  workTime: "Пн-Сб 09:00-18:00",
  instagram: "@jdmparts.kz",
  facebook: "JDM Parts Kazakhstan",
  telegram: "@jdmparts",
  heroTitle: "Автозапчасти для Toyota, Lexus, Hyundai и Kia",
  heroSubtitle: "Оставьте заявку - мы подберём нужную деталь по марке, модели или VIN-коду.",
  aboutText: "JDM PARTS помогает быстро подобрать японские и корейские автозапчасти под ваш автомобиль.",
  footerText: "Подбор автозапчастей по VIN и параметрам автомобиля.",
  requisites: "ИП / ТОО: JDM PARTS\nБИН/ИИН: 000000000000\nБанк: Kaspi Bank\nIBAN: KZ000000000000000000",
  commercialSignature: "С уважением, JDM PARTS",
};
